import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const executablePath=process.env.BROWSER_PATH || path.join(process.env.LOCALAPPDATA,'ms-playwright','chromium-1234','chrome-win64','chrome.exe');
const browser=await chromium.launch({headless:true,executablePath,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('test-results',{recursive:true});
try{
  await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>window.__blast?.renderer.info.render.calls>0);
  await page.screenshot({path:'test-results/menu-desktop.png'});
  await page.getByRole('button',{name:'INICIAR OPERACIÓN'}).click();
  await page.keyboard.down('KeyW');await page.waitForTimeout(1000);await page.keyboard.up('KeyW');
  let state=await page.evaluate(()=>({z:__blast.game.player.z,state:__blast.game.state,time:__blast.game.time}));
  assert.equal(state.state,'playing');assert.ok(state.z<41,`Vehicle should move: ${state.z}`);
  await page.keyboard.press('Digit3');
  assert.equal(await page.evaluate(()=>__blast.game.player.vehicle),2);
  await page.keyboard.press('Space');await page.waitForTimeout(300);
  assert.ok(await page.evaluate(()=>__blast.game.cleared>0),'Titan should demolish a route obstacle');
  await page.screenshot({path:'test-results/game-desktop.png'});
  await page.keyboard.press('Escape');
  const pausedTime=await page.evaluate(()=>__blast.game.time);await page.waitForTimeout(350);
  assert.equal(await page.evaluate(()=>__blast.game.time),pausedTime);
  await page.getByRole('button',{name:'CONTINUAR →'}).click();
  await page.evaluate(()=>{__blast.game.buildings.forEach(b=>__blast.game.hit(b,9999));__blast.game.convoy.z=-59.99});
  await page.waitForFunction(()=>__blast.game.state==='won');
  await page.getByRole('heading',{name:'Camino despejado.'}).waitFor();
  assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('blast-recharged-records'))[0]>0));
  await page.screenshot({path:'test-results/victory.png'});
  await page.getByRole('button',{name:'SIGUIENTE OPERACIÓN'}).click();
  assert.equal(await page.evaluate(()=>__blast.game.index),1);
  await page.evaluate(()=>{__blast.game.convoy.z=__blast.game.buildings[0].z+3;__blast.game.convoy.hp=.1});
  await page.getByRole('heading',{name:'Carga perdida.'}).waitFor();
  await page.getByRole('button',{name:'VOLVER A OPERACIONES'}).click();
  await page.getByRole('button',{name:'03 / CENTRO'}).click();
  assert.equal(await page.evaluate(()=>__blast.game.index),2);
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(400);
  await page.screenshot({path:'test-results/menu-mobile.png'});
  const startBox=await page.locator('#start').boundingBox();assert.ok(startBox.y+startBox.height<844,'Start button must be visible on mobile');
  await page.getByRole('button',{name:'INICIAR OPERACIÓN'}).click();
  await page.waitForTimeout(1300);
  await page.screenshot({path:'test-results/game-mobile.png'});
  assert.equal(await page.locator('.touch-controls').isVisible(),true);
  const forward=page.locator('[data-key="KeyW"]');await forward.dispatchEvent('pointerdown',{pointerId:1});await page.waitForTimeout(350);await forward.dispatchEvent('pointerup',{pointerId:1});
  await page.getByRole('button',{name:'Activar audio',exact:true}).click();
  await page.getByRole('button',{name:'Silenciar audio',exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result:'passed',checks:['WebGL render','keyboard driving','vehicle switch','demolition','pause freezes simulation','victory and saved record','next mission','failure','mission picker','responsive menu','touch controls','audio toggle'],render:await page.evaluate(()=>({calls:__blast.renderer.info.render.calls,triangles:__blast.renderer.info.render.triangles}))},null,2));
}finally{await browser.close()}
